Filelock management tests
notanumber/xapian-haystack pull request #219
Opened 2022-02-05 02:21 UTC by ajslater

## Problem
If xapian-haystack is used today with more than one worker it breaks with xapian.DatabaseLockError

## Solution
This solution was cribbed from [@karolyi](https://github.com/karolyi) in his issue report: [#174](https://github.com/notanumber/xapian-haystack/issues/174) . 
I implement a lockfile decorator around the update() and remove() methods.

## Decisions

It paces the lockfile in the xapian-index directory, which should affect performance.

## Tests

This PR includes a new `test_management_commands.py` test suite that runs the management commands. This test suite fails if the lockfile isn't implemented as you can see in this branch: https://github.com/ajslater/xapian-haystack/actions/runs/1798091039

## Workarounds

This PR can be used as inspiration for an easy workaround for this issue. Subclass XapianSearchBackend and BaseEngine with these changes. and use that in your Haystack settings. Example here: https://github.com/ajslater/codex/blob/develop/codex/search_engine.py

2022-02-05 09:34 UTC, claudep requested changes
Thanks! We are on the right track :-) I'll work on removing Python 3.6 support to simplify things a bit.

2022-02-05 09:34 UTC, claudep commented on .github/workflows/test.yml
> +        xapian-version: ["1.4.18"]
Please do not include unrelated changes in the patch,

2022-02-05 09:34 UTC, claudep commented on requirements.txt
> +filelock~=3.4.1
I would just depend on `filelock>=3.4`. We may drop Python 3.6 support soon (but for another PR).

2022-02-05 09:34 UTC, claudep commented on .github/workflows/test.yml
> +        filelock-version: ["3.4.1"]
As already commented, I'd rather suggest dropping Python 3.6 support and we can get rid of `filelock-version` stuff in this file.

2022-02-05 09:34 UTC, claudep commented on tests/xapian_tests/tests/test_management_commands.py
> +    # fixtures = ["bulk_data"]
If we don't need it, drop it!

2022-02-05 09:34 UTC, claudep commented on tests/xapian_tests/tests/test_management_commands.py
> +    NUM_BLOG_ENTRIES = 100
Is there a reason we need 100?

2022-02-05 09:34 UTC, claudep commented on tests/xapian_tests/tests/test_management_commands.py
> +import datetime
I'd love to see this test file with tests unrelated to the present issue suggested as a separate PR.

2022-02-05 09:34 UTC, claudep commented on xapian_backend.py
> +            self.lockfile.parent.mkdir(parents=True)
Shouldn't the parent path be created earlier in the backend `__init__` method?

2022-02-05 09:34 UTC, claudep commented on xapian_backend.py
> +        self.lockfile = Path(self.path) / "lockfile"
AFAICS we don't need to set the lockfile on self. We should be able to refer to the file with self.filelock.lock_file when needed.

2022-02-05 10:05 UTC, claudep commented
I think we should still add a new custom connection option to opt out of the lock, so people not needing a multiprocess access have a way to keep better performances by not using the lock.

2022-02-05 10:06 UTC, claudep commented
By the way, the minimal Python version is now 3.7.
https://github.com/notanumber/xapian-haystack/commit/77d1fc8ef650ccd4dcd674611b99bc8ac2886a7c

2022-02-06 19:47 UTC, ajslater commented on tests/xapian_tests/tests/test_management_commands.py
> +import datetime
Done.

2022-02-06 19:48 UTC, ajslater commented on xapian_backend.py
> +        self.lockfile = Path(self.path) / "lockfile"
I agree. This has been changed.

2022-02-06 19:52 UTC, ajslater commented on xapian_backend.py
> +            self.lockfile.parent.mkdir(parents=True)
That's what i thought too. However the backend.clear() method destroys the entire xapian-index directory with shutil. xapian database or something ends up recreating it, maybe, but that happens after our file locking with update, so tests will fail without this and it seems that users who use the clear() or rebuild_index() method could jam themselves up on it too.

2022-02-06 19:53 UTC, ajslater commented on tests/xapian_tests/tests/test_management_commands.py
> +    NUM_BLOG_ENTRIES = 100
I tweaked some other test params and seem to be able to replicate the issue with 20.

2022-02-06 19:53 UTC, ajslater commented on tests/xapian_tests/tests/test_management_commands.py
> +    # fixtures = ["bulk_data"]
Woops. Thanks. Done.

2022-02-06 19:56 UTC, ajslater commented on .github/workflows/test.yml
> +        filelock-version: ["3.4.1"]
This is my first time using github actions, but this test suite appears to fail if filelock isn't explicitly installed in the  "Install Django and other Python dependencies" step below. The matrix here seems a convenient place to store the version number next to the other version numbers.  Also worth looking at is that you may have a comment on that i've added django 4.0 to the python 3.10 test.

2022-02-06 19:57 UTC, ajslater commented on requirements.txt
> +filelock~=3.4.1
Done. If filelock 4 ever comes out and breaks this, we'll deal with that then.

2022-02-06 19:58 UTC, ajslater commented on .github/workflows/test.yml
> +        xapian-version: ["1.4.18"]
Woops. I must've activated my personal linter in the wrong place. Restored to the original quotes.

2022-02-06 20:06 UTC, ajslater commented
I've fixed or commented on all the requested changes. Take another look. An addition I've made is that I noticed that backend.path can be an in-memory database so i've disabled the filelock in that case.

I can't find the comment, but I recall you asking if we might provide an option for people not to use filelocking. Should I add a boolean flag to connection_options?

2022-02-06 21:35 UTC, claudep commented on tests/xapian_tests/tests/test_management_commands.py
> +import datetime
Could you please provide the separate PR with the other passing tests?

2022-02-06 21:37 UTC, claudep commented on .github/workflows/test.yml
> +        filelock-version: ["3.4.1"]
I would simply drop any change to `test.yml` in this patch. Testing Python 3.10 or Django 4.0 should be another issue/PR. And filelock should be installed as part of dependencies installation.

2022-02-06 21:39 UTC, claudep commented on tests/xapian_tests/tests/test_backend.py
> +from pathlib import Path
Looks like this import is now unneeded.

2022-02-06 21:41 UTC, claudep commented on xapian_backend.py
> +                Path(self.path).mkdir(parents=True)
You can pass `exist_ok=True` to avoid the try/except clause.

2022-02-06 21:42 UTC, claudep commented
> I can't find the comment, but I recall you asking if we might provide an option for people not to use filelocking in general. Should I add a boolean flag to connection_options?

Yes, please.

2022-02-07 00:03 UTC, ajslater commented on tests/xapian_tests/tests/test_backend.py
> +from pathlib import Path
Thanks. Removed.

2022-02-07 00:03 UTC, ajslater commented on xapian_backend.py
> +                Path(self.path).mkdir(parents=True)
Ah right. Python 3.4, I had remembered it as later. Fixed.

2022-02-07 00:04 UTC, ajslater commented
Latest commits include the USE_LOCKFILE connection parameter with a short documentation line.

2022-02-07 00:12 UTC, ajslater commented on tests/xapian_tests/tests/test_management_commands.py
> +import datetime
Separate PR here: https://github.com/notanumber/xapian-haystack/pull/221

2022-02-07 17:01 UTC, claudep commented on xapian_backend.py
> +        self.use_lockfile = connection_options.get('USE_LOCKFILE', True)
Thanks for the flag addition. I would pop the option before the `super().__init__` call to avoid passing it to the BaseSearchBackend.

2022-02-07 17:10 UTC, claudep commented on README.rst
> +  Defaults to `True`.
The above settings (`HAYSTACK_XAPIAN_*`) are supposed to be project settings, not connection options. So we should decide if our lockfile option should be a setting (then renaming it as `HAYSTACK_XAPIAN_USE_LOCKFILE`) or letting it as a connection option and move these lines above. I guess that for consistency, the former should be done? What do you think?

2022-02-07 17:11 UTC, claudep commented on .github/workflows/test.yml
> +        filelock-version: ["3.4.1"]
Still todo?

2022-02-07 20:15 UTC, ajslater commented on .github/workflows/test.yml
> +        filelock-version: ["3.4.1"]
- I've restored the django 4.0 include version back to 3.2
- The python 3.10 matrix & include requirements were added six months ago.
- The filelock-version additions appear to be necessary.  Specifically, the tests fail importing filelock if the dependency installations on line 75 does not install filelock.

2022-02-07 20:21 UTC, ajslater commented on xapian_backend.py
> +        self.use_lockfile = connection_options.get('USE_LOCKFILE', True)
Good idea. Done. 
I've also casted it to a bool just so it doesn't end up with an unexpected value.

2022-02-07 20:26 UTC, claudep commented on .github/workflows/test.yml
> +        filelock-version: ["3.4.1"]
Ah, I understand now, the `test.yml` doesn't use the requirements.txt. Sorry, you are right.

2022-02-07 20:27 UTC, ajslater commented on README.rst
> +  Defaults to `True`.
I've changed it to setting named to HAYSTACK_XAPIAN_USE_LOCKFILE

2022-02-07 20:28 UTC, ajslater commented on README.rst
> +  Defaults to `True`.
Fixed typo. Thanks.

2022-02-07 20:29 UTC, ajslater commented on xapian_backend.py
> +        self.use_lockfile = connection_options.get('USE_LOCKFILE', True)
This was also changed to a setting from a connection option

2022-02-07 20:32 UTC, claudep commented on tests/xapian_tests/tests/test_management_commands.py
> +        )
According to https://docs.djangoproject.com/en/4.0/ref/django-admin/#output-redirection, you should be able to capture stderr with the `stderr=` param of `call_command`.

2022-02-07 20:38 UTC, ajslater commented on tests/xapian_tests/tests/test_management_commands.py
> +        )
I tried that and it didn't work. 
It turns out for that to work the Command implementer has to explicitly send prints to print("blah", stderr=self.stderr), where self is BaseCommand. And I think these messages aren't even coming from python, but the underlying xapian database implementation.

2022-02-07 20:52 UTC, ajslater commented on tests/xapian_tests/tests/test_management_commands.py
> +        )
Also, the failure mode for this test is only occasionally parsing that stderr string. Most of the time call_command() throws an exception and halts the test before the assert.

2022-02-08 20:10 UTC, ajslater commented
Merged from upstream and and added a CHANGELOG item.

2022-02-09 19:46 UTC, claudep commented
Thanks, I think this is now ready. Only rebase and we are done.

2022-02-09 22:09 UTC, ajslater commented
Rebased on current master.

2022-02-10 19:44 UTC, merged